---
- name: This playbook installs package
  hosts: webservers
  become: true

  tasks:
  - name: Installing a package
    yum:
     name: ['git', 'make', 'httpd', 'wget', 'tree', 'which', 'docker']
     state: installed
