---
- name: installing tomact application
  hosts: all
  become: true
  tasks: 
  - name: Install java on RedHat
    yum:       
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
      dest: /opt

  - name: Extract tomcat package
    unarchive:
      src: /opt/apache-tomcat-8.5.68.tar.gz
      dest: /opt
      remote_src: yes

  - name: Give exec permissions
    file:
      path: /opt/apache-tomcat-8.5.68/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.68/bin 

 
